name: Deploy no NPM

on:
  push:
    branches:
      - main # Branch principal para publicação de versões estáveis
      - test # Branch para publicação de versões de teste

jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Verificar alterações no diretório dist
      id: check_dist
      run: |
        git fetch --depth=2
        PREV_COMMIT=$(git log -n 1 --skip=1 --pretty=format:%H || echo ${{ github.sha }})
        if git diff --name-only $PREV_COMMIT HEAD | grep '^dist/'; then
          echo "dist changes"
          echo "::set-output name=result::dist changes"
        else
          echo "no dist changes"
          echo "::set-output name=result::no dist changes"
          exit 0
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - name: Build the library and add tags
      run: npm run build

    - name: Publish to NPM
      if: ${{ steps.check_dist.outputs.result == 'dist changes' }}
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}  # Usando o token armazenado nos secrets
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

        cd dist/ngx-sp-infra
        
        # Condicional para definir a tag de publicação
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          npm publish --access public --tag latest
        elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
          npm publish --access public --tag test
        fi
